apiVersion: v2.edp.epam.com/v1alpha1
kind: Sonar
metadata:
  name: example-sonar
spec:
  type: "Sonar"
  version: "7.1"
  volumes:
    - name: "data"
      storage_class: "efs"
      capacity: "1Gi"
    - name: "db"
      storage_class: "efs"
      capacity: "1Gi"

