apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonar-operator-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      name: sonar-operator-v2
  template:
    metadata:
      labels:
        name: sonar-operator-v2
    spec:
      serviceAccountName: edp
      securityContext:
        runAsUser: 1001 
        runAsNonRoot: true
        runAsGroup: 1001
        fsGroup: 1001
      containers:
        - name: sonar-operator-v2
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - sonar-operator
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
          env:
            - name: WATCH_NAMESPACE
              value: REPLACE_VALUE
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "sonar-operator-v2"
            - name: PLATFORM_TYPE
              value: "openshift"
